# Generated by Django 4.0 on 2022-07-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authemail', models.EmailField(max_length=100)),
                ('authusername', models.CharField(max_length=100)),
                ('authpassword', models.CharField(max_length=100)),
            ],
        ),
    ]
