# Generated by Django 4.0 on 2022-07-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_clients_authusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='authusername',
            field=models.CharField(max_length=100),
        ),
    ]
