# Generated by Django 4.0 on 2022-07-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_clients_authusername'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Custmers',
        ),
    ]
